[MM-768]: Updated client structure in plugin and added testcase for command.go file
Brightscout/mattermost-plugin-msteams-meetings pull request #6
Opened 2024-09-16 09:28 UTC by Kshitij-Katiyar

### Summary
Updated client structure in plugin and added testcase for command.go file

2024-09-23 04:03 UTC, raghavaggarwal2308 requested changes

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/authorization.go
> +		p.client = p.NewClient(conf, token)
We have already initialised the client on used connect, do we need to do it here?

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +type MockClient struct {
We do not need to mock it manually since this is an interface. You can use mockgen

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			mockSetup: func(api *plugintest.API, encryptedUserInfo []byte, mockTracker *MockTracker, mockClient *MockClient) {
mockTracker is not getting used, i think we can remove it

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			mockSetup: func(api *plugintest.API, encryptedUserInfo []byte, mockTracker *MockTracker, mockClient *MockClient) {
Check everywhere

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +					Driver: &plugintest.Driver{},
Do we need this?

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			expectedError: "error getting user for the userId",
```suggestion
			expectedError: "error getting user for the userID",
```

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +				api.On("GetUser", "demoUserId").Return(nil, &model.AppError{Message: "error getting user for the userId"})
```suggestion
				api.On("GetUser", "demoUserId").Return(nil, &model.AppError{Message: "error getting user for the userID"})
```

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			expectedError: "error getting user for the userId",
Check everywhere

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			name:        "Check Previous Message error",
Write proper name

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +					HasNext:                   false,
Do we need to initialize these? These are default values

2024-09-23 04:03 UTC, raghavaggarwal2308 commented on server/command_test.go
> +					HasNext:                   false,
Check everywhere

2024-09-23 12:31 UTC, Kshitij-Katiyar commented on server/command_test.go
> +			mockSetup: func(api *plugintest.API, encryptedUserInfo []byte, mockTracker *MockTracker, mockClient *MockClient) {
I think it is being used at all the places it is placed, we can discuss it tho.

2024-09-23 12:51 UTC, Kshitij-Katiyar commented on server/authorization.go
> +		p.client = p.NewClient(conf, token)
Kept the functionality for creating a new client with token for this [line](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings/blob/master/server/http.go#L137).
let me know if it is not needed in your opinion

2024-09-23 13:44 UTC, Kshitij-Katiyar commented on server/command_test.go
> +			mockSetup: func(api *plugintest.API, encryptedUserInfo []byte, mockTracker *MockTracker, mockClient *MockClient) {
discussed

2024-09-23 13:44 UTC, Kshitij-Katiyar commented on server/command_test.go
> +type MockClient struct {
discussed

2024-09-27 08:17 UTC, raghavaggarwal2308 commented on server/authorization.go
> +		p.client = p.NewClient(conf, token)
Implemented as discussed

2024-09-27 08:32 UTC, raghavaggarwal2308 approved these changes

2024-09-30 18:29 UTC, raghavaggarwal2308 commented
Created PR with the changes on MM

2024-09-30 18:29 UTC, closed without merging