[MM-822]: Added testcases for http.go
Brightscout/mattermost-plugin-msteams-meetings pull request #8
Opened 2024-10-01 09:31 UTC by Kshitij-Katiyar

### Summary
Added testcases for http.go

#### Note
Unable to add testcase `completeUserOauth` function after the [line](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings/blob/5121affd95c4596f58050f9d927b1dbc142b51f9/server/http.go#L130) as we were unable to mock the external API call made by this line's function.

2024-10-04 14:08 UTC, raghavaggarwal2308 requested changes

2024-10-04 14:08 UTC, raghavaggarwal2308 commented on server/http_test.go
> +	}
Should not be global

2024-10-04 14:08 UTC, raghavaggarwal2308 commented on server/http_test.go
> +			redirectExpected:    false,
remove, check everywhere

2024-10-04 14:08 UTC, raghavaggarwal2308 commented on server/http_test.go
> +			channelID:           "testChannelID",
Never changing, can remove

2024-10-07 09:26 UTC, Kshitij-Katiyar commented on server/http_test.go
> +			channelID:           "testChannelID",
it is needed for the line
`req := httptest.NewRequest(http.MethodGet, "/oauth2/connect?channelID="+tt.channelID, nil)`
for the testcase
`name:                "Missing Channel ID",`

2024-10-07 09:26 UTC, Kshitij-Katiyar commented on server/http_test.go
> +			channelID:           "testChannelID",
same for user id

2024-10-07 10:06 UTC, raghavaggarwal2308 requested changes

2024-10-07 10:06 UTC, raghavaggarwal2308 commented on server/http_test.go
> +			expectedBody:   "error fetching siteUrl\n",
```suggestion
			expectedBody:   "error fetching siteURL\n",
```

2024-10-07 10:06 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			response, _ := p.ExecuteCommand(&dummyPluginContext, &tt.commandArgs) // #nosec G601
Why have we added nosec

2024-10-09 07:18 UTC, raghavaggarwal2308 approved these changes

2024-10-10 08:54 UTC, Kshitij-Katiyar commented
Created a PR on mattermost remote with all these changes hence closing this one

2024-10-10 08:54 UTC, closed without merging